# Generated by Django 6.0.3 on 2026-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='В топе'),
        ),
    ]
