# Generated by Django 6.0.3 on 2026-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_ad_vip_requested_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения товара'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(max_length=500, verbose_name='URL баннера'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL иконки'),
        ),
    ]
